### ISSUE TITLE
change text All lights on/off

### ISSUE THREAD

**Issue by Fisico** [mariusmotea/DiyHueReact#21]
In the topbar toggle the text with the toggleswitch from on to off.
![image](https://user-images.githubusercontent.com/329471/135715547-7f711214-58bc-40a9-8492-948bd4b9fd60.png)

Div structure:
```
<div className="onbtn">
        <p>All lights on/off</p>
```

**Comment by mariusmotea** [comment]
i changed this to "Turn all lights off" or "Turn all lights on" since this is the action the button do. If his state is on it means at last one light is on, not all.
